### ISSUE TITLE
Roadmap 0.0.2

### ISSUE THREAD

**Issue by zuoxingdong** [zuoxingdong/lagom#4]
Here we list some todos for next release of `0.0.2`

- [x] Global `make_env` and return EnvSpec. Similar to OpenAI baselines, handle all kinds of environments and make use of functiontools.partial to return argument-free functions

- [x] Support most of function in Network to Policy/Agent class:   
    1. `to(device)`
    2. `num_params`
    3. `train()/eval()`
    4. Might be more networks in one policy.
    5. How to group all networks being trackable with internal methods. ModuleList ? such as `num_params` with all networks together. 

- [x] New logger: avoid hierarchical structure of mixture of list, dictionary and ndarray. Pickling it will be extremely slow. Keep only top level as dictionary. Add function with similar to add_tabular. 

- [x] Where to handle dtype conversion from numpy to Tensor. Suggested in `Agent.choose_action`

- [x] Supports VecEnv
    1. StackObservation
    2. VecWrapper
    3. VecNormalize

- [x] Adapts all standard Agent to both single Env and VecEnv

- [x] Write a function to automatically split config IDs with a key

- [x] Write `__repr__` for string representation, e.g. Transition/Segment, EnvSpec...

- [x] Add GAE to Trajectory and Segment

- [x] Add non-rolling VecEnv, returning zero for terminated sub-environments, and update TrajectoryRunner to make it more efficient, remove argument N, only with T.
